name: braincloud
description: "brainCloud is a backend platform for mobile games and apps, offering robust features, tools, and support. braincloud package enables use of brainCloud in Dart and Flutter projects."
version: 5.5.0+2
homepage: "https://getbraincloud.com/"

environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.3
  dart_ping: ^9.0.1
  dio: ^5.7.0
  event: ^3.0.1
  archive: ^4.0.2
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  tcp_client_dart: ^0.2.0
  test: ^1.25.7
  udp: ^5.0.3
  universal_io: ^2.2.2
  uuid: ^4.5.1
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  analyzer: 
  args: ^2.5.0

documentation: "https://docs.braincloudservers.com/api/introduction"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - braincloud
  
